<footer id="footend">

	<div class="container">

		<div class="grid">

			<div class="grid-item item-contact">

				<div class="wrapper">
					
					<?php print render($page['footend_one']); ?>

				</div>

			</div>

			<div class="grid-item item-comm">

				<div class="wrapper">
					
					<?php print render($page['footend_two']); ?>
                    <a href="http://test.astd.co.za/member" class="member-link">Read about the membership benefits</a>
                    
				</div>

			</div>

			<div class="grid-item item-three">

				<div class="wrapper">

					<?php print render($page['footend_three']); ?>
					
				</div>

			</div>

		</div>

	</div>

</footer>